# version: '3.9'

services:
  postgres:
    image: postgres:13.21-alpine3.21
    container_name: postgres-db
    environment:
      POSTGRES_USER: dudung
      POSTGRES_PASSWORD: dudung123
      POSTGRES_DB: dudungdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "unix_socket_directories=/var/run/postgresql"]
    networks:
      - pgnet

volumes:
  pgdata:

networks:
  pgnet:
    name: pgnet
