services:
  oracle-db-19c:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle-db-19c
    ports:
      - "1521:1521" # Host port 1521, container port 1521
      - "5500:5500"
    environment:
      DB_SID: ORCL
      ORACLE_PWD: sapassword
      DB_PDB: ORAGIRIPDB
      DB_DOMAIN: oracledb.giri.local
      ENABLE_ARCHIVELOG: "true"
    volumes:
      - oracle-data-19c:/opt/oracle/oradata
      - oracle-backup-19c:/opt/oracle/backup
    restart: unless-stopped

volumes:
  oracle-data-19c:
    driver: local
  oracle-backup-19c:
    driver: local