services:
  oracle-db-12c:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    ports:
      - "1521:1521" # Host port 1521, container port 1521
    environment:
      DB_SID: ORCL
      ORACLE_PWD: sapassword
      DB_PDB: ORAGIRIPDB
      DB_DOMAIN: oracledb.giri.local
      ENABLE_ARCHIVELOG: "true"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    restart: unless-stopped

volumes:
  oracle-data:
    driver: local
  oracle-backup:
    driver: local